obj-$(CONFIG_MACH_M8) += htc_m8-panel.o
obj-$(CONFIG_MACH_M8_DUG) += htc_m8-panel.o
obj-$(CONFIG_MACH_M8_WHL) += htc_m8-panel.o
obj-$(CONFIG_MACH_M8_WL) += htc_m8-panel.o
obj-$(CONFIG_MACH_MELS_TUHL) += htc_m8-panel.o
obj-$(CONFIG_MACH_EYE_UL) += htc_eye-panel.o
